export enum Routes {
    home = "/",
    becomeADealer = "/become-a-dealer",
    allProducts = '/all-products',
    allProductsSiding = '/all-products#siding',
    allProductsDecking = '/all-products#decking',
    allProductsNarrow = '/all-products#narrow',
    allProductsStandard = '/all-products#standard',
    allProductsUltra = '/all-products#ultra',
    allProductsDeckTiles = '/all-products#decktiles',
    allProductsPostBeams = '/all-products#posts&beams',
    allProductsFacades = '/all-products#facades',
    allProductsPergolas = '/all-products#pergolas',
    allProductsFencing = '/all-products#fencing',
    allProductsWoodTrim = '/all-products#woodtrim',
    allProjects = '/all-projects',
    productDetails = '/product-details',
    hardwood = '/hardwood',
    thermowood = '/thermo',
    contactus = '/contact-us',
    resources = '/resources',
    resourcesHardwood = '/resources#hardwood',
    resourcesThermo = '/resources#thermo',
    resourcesSamples = '/resources#samples',
    resourcesScheduleCeu = '/resources#scheduleceu',
}