import { Product } from "./types";

export const HardWoodList: Product[] = [
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "1x4 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking"],
            collection: "Narrow",
        },
        description: "Maximo Ipe stands as the ultimate hardwood choice, unmatched in strength, durability, and longevity. With its unparalleled hardness and resistance, Maximo Ipe outperforms every other lumber on the market. Our precision kiln-drying process enhances its structural performance, significantly reducing post-installation movement, including warping, twisting, and bowing. Homeowners and architects alike choose Maximo Ipe in a 1x4 profile for its narrow, refined look, making it the preferred option for creating timeless, elegant porch floors that are built to last.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 1,
        images: [
          '/images/hardwood/Ipe/1x4 S4SE4E/Maximo Hardwood Ipe 1x4 S4SE4E- 1.jpg',
          '/images/hardwood/Ipe/1x4 S4SE4E/Maximo Hardwood Ipe 1x4 S4SE4E - 2.jpg',
          '/images/hardwood/Ipe/1x4 S4SE4E/1x4 ipe.webp',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "5/4x4 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking"],
            collection: "Narrow",
        },
        description: "Maximo Ipe stands as the ultimate hardwood choice, unmatched in strength, durability, and longevity. With its unparalleled hardness and resistance, Maximo Ipe outperforms every other lumber on the market. Our precision kiln-drying process enhances its structural performance, significantly reducing post-installation movement, including warping, twisting, and bowing. The 5/4x4 profile adds extra thickness to each board while maintaining the narrow, refined look that architects and homeowners prefer for porch flooring, ensuring a perfect balance of durability and aesthetic appeal.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 2,
        images: [
          '/images/hardwood/Ipe/5-4x4 S4SE4E/Maximo Hardwood Ipe 5-4X4 S4SE4E - 1.jpg',
          '/images/hardwood/Ipe/5-4x4 S4SE4E/Maximo Hardwood Ipe 5-4X4 S4SE4E - 2.jpg',
          '/images/hardwood/Ipe/5-4x4 S4SE4E/patina_hotel_279.JPG',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "1x6 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking", "Fencing"],
            collection: "Standard",
        },
        description: "For those seeking the finest in decking, Maximo Ipe delivers unmatched strength, durability, and one-of-a-kind aesthetics. Known for its superior hardness and long-lasting performance, Maximo offers this Ipe in a classic, robust 1x6 profile. Kiln-dried for enhanced stability, it combines a timeless appeal with a sophisticated look, perfect for elevating any outdoor space.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking Fencing",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 3,
        images: [
          '/images/hardwood/Ipe/1x6 S4SE4E/Maximo Hardwood Ipe 1x6 S4SE4E - 1.jpg',
          '/images/hardwood/Ipe/1x6 S4SE4E/Maximo Hardwood Ipe 1x6 S4SE4E - 2.jpg',
          '/images/hardwood/Ipe/1x6 S4SE4E/1x6 ipe.webp',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "5/4x6 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking"],
            collection: "Standard",
        },
        description: "For those seeking the finest in decking, Maximo Ipe delivers unmatched strength, durability, and one-of-a-kind aesthetics. Known for its superior hardness and long-lasting performance, Maximo offers this Ipe in a sturdy 5/4x6 profile. Kiln-dried for enhanced stability and reduced movement, this thicker option provides an even more solid feel underfoot while maintaining a timeless, sophisticated look.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 4,
        images: [
          '/images/hardwood/Ipe/5-4X6 S4SE4E/Maximo Hardwood Ipe 5-4X6 S4SE4E - 1.jpg',
          '/images/hardwood/Ipe/5-4X6 S4SE4E/Maximo Hardwood Ipe 5-4X6 S4SE4E - 2.jpg',
          '/images/hardwood/Ipe/5-4X6 S4SE4E/138f.webp',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "1x8 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking", "Fencing"],
            collection: "Ultra Wide",
        },
        description: "For those seeking a striking statement in their decking, Maximo Ipe delivers unmatched strength, durability, and stunning aesthetics. Known for its superior hardness and long-lasting performance, this Ipe is offered in a wide 1x8 profile, perfect for achieving a bold, expansive look. Kiln-dried for enhanced stability, this profile is not only ideal for decking but also serves as a perfect choice for fascias and finishing touches, elevating any project with its refined elegance.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking Fencing",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 5,
        images: [
          '/images/hardwood/Ipe/1x8 S4SE4E/Maximo Hardwood Ipe 1x8 S4SE4E - 1.jpg',
          '/images/hardwood/Ipe/1x8 S4SE4E/Maximo Hardwood Ipe 1x8 S4SE4E - 2.jpg',
          '/images/hardwood/Ipe/1x8 S4SE4E/_DSC6073.jpg',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "1x12 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking", "Fencing"],
            collection: "Ultra Wide",
        },
        description: "If you’re looking to create a bold and lasting impression in your outdoor spaces, Maximo Ipe delivers unmatched strength, durability, and breathtaking aesthetics. Known for its superior hardness and long-lasting performance, this ultra-wide 1x12 profile makes a striking statement that transforms any deck into a stunning centerpiece. Kiln-dried for enhanced stability, the 1x12 profile is perfect for expansive decking areas, as well as fascias and finishing applications.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking Fencing",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 6,
        images: [
          '/images/hardwood/Ipe/1x12 S4SE4E/Maximo Hardwood Ipe 1x12 S4SE4E -1.jpg',
          '/images/hardwood/Ipe/1x12 S4SE4E/Maximo Hardwood Ipe 1x12 S4SE4E -2.jpg',
          '/images/hardwood/Ipe/1x12 S4SE4E/1x12 ipe.webp',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "2x2 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Pergolas", "Posts & Beams"],
            collection: ""
        },
        description: "Maximo Ipe 2x2 posts are crafted to create sturdy and elegant structures in your outdoor living spaces. Known for its superior hardness and durability, Maximo Ipe ensures that these posts withstand the elements while providing a refined look. Ideal for supporting pergolas and other architectural features, the 2x2 profile offers both strength and beauty, making it a fantastic addition to any outdoor project.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Pergolas Posts & Beams",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 7,
        images: [
          '/images/hardwood/Ipe/2x2 S4SE4E/Maximo Hardwood Ipe 2x2 S4SE4E - 1.jpg',
          '/images/hardwood/Ipe/2x2 S4SE4E/Maximo Hardwood Ipe 2x2 S4SE4E - 2.jpg',
          '/images/hardwood/Ipe/2x2 S4SE4E/_DSC9994.jpg',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "4x4 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Pergolas", "Posts & Beams"],
            collection: ""
        },
        description: "Maximo Ipe 4x4 posts are designed for those looking to build strong and beautiful outdoor structures. Known for its superior hardness and long-lasting performance, these posts not only provide structural integrity but also enhance the visual appeal of your outdoor space. Perfect for supporting pergolas, arbors, or as posts for fencing, the 4x4 profile ensures that your project stands the test of time.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Pergolas Posts & Beams",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 8,
        images: [
          '/images/hardwood/Ipe/4x4 S4SE4E/Maximo Hardwood Ipe 4x4-1.jpg',
          '/images/hardwood/Ipe/4x4 S4SE4E/Maximo Hardwood Ipe 4x4-2.jpg',
        ]
    },
    {
        group: "Ipe",
        name: "Maximo Hardwood Ipe",
        dimensions: "6x6 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Pergolas", "Posts & Beams"],
            collection: ""
        },
        description: "Maximo Ipe 6x6 posts are built for maximum strength and durability, making them the ideal choice for any outdoor structure. Known for its superior hardness and resistance to the elements, these posts provide unmatched support for pergolas, gazebos, or other large structures while offering a stunning, natural look. The 6x6 profile is perfect for creating a focal point in your outdoor area, enhancing both functionality and aesthetics.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Pergolas Posts & Beams",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 9,
        images: [
          '/images/hardwood/Ipe/6x6 S4SE4E/Maximo Hardwood Ipe 6X6 S4SE4E - 1.jpg',
          '/images/hardwood/Ipe/6x6 S4SE4E/Maximo Hardwood Ipe 6X6 S4SE4E - 2.jpg',
          '/images/hardwood/Ipe/6x6 S4SE4E/187-2.jpg',
        ]
    },
    {
        group: "Cumaru",
        name: "Maximo Hardwood Cumaru",
        dimensions: "8x8 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Posts & Beams", "Pergolas"],
            collection: "",
        },
        description: "These Maximo Hardwood Cumaru 8x8 posts provide exceptional power and stability for grand outdoor designs. Crafted from durable, sustainable South-American Cumaru wood, these robust posts are ideal for supporting large-scale structures, ensuring beauty and resilience in every application.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Posts & Beams Pergolas",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 13,
        images: [
          '/images/hardwood/Cumaru/Cumaru 8x8 S4SE4E/Maximo Hardwood Cumaru 8x8 S4SE4E -1.jpg',
          '/images/hardwood/Cumaru/Cumaru 8x8 S4SE4E/Maximo Hardwood Cumaru 8x8 S4SE4E -2.jpg',
          '/images/hardwood/Cumaru/Cumaru 8x8 S4SE4E/_DSC4206.jpg',
        ]
    },
    {
        group: "Cumaru",
        name: "Maximo Hardwood Cumaru",
        dimensions: "10x10 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Posts & Beams", "Pergolas"],
            collection: "",
        },
        description: "Maximo Hardwood Cumaru 10x10 posts deliver ultimate strength and stability for stately outdoor structures. Known for its density and durability, Maximo Cumaru ensures projects will withstand the test of time while adding a sophisticated look to any landscape.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Posts & Beams Pergolas",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 14,
        images: [
          '/images/hardwood/Cumaru/Cumaru 10x10 S4SE4E/Maximo Hardwood  Cumaru 10x10 S4SE4E -1.jpg',
          '/images/hardwood/Cumaru/Cumaru 10x10 S4SE4E/Maximo Hardwood  Cumaru 10x10 S4SE4E -2.jpg',
          '/images/hardwood/Cumaru/Cumaru 10x10 S4SE4E/_DSC0743-2.jpg',
        ]
    },
    {
        group: "Cumaru",
        name: "Maximo Hardwood Cumaru",
        dimensions: "12x12 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Posts & Beams", "Pergolas"],
            collection: "",
        },
        description: "Monumental outdoor projects deserve monumental support, and Maximo Hardwood Cumaru 12x12 posts deliver just that. Offered in lengths of 3 to 22 feet, these posts provide unmatched stability and strength, making them the ideal choice for large pergolas and other significant structures. Crafted from the finest Cumaru, they combine exceptional performance with breathtaking aesthetics, ensuring your projects stand the test of time with style.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Posts & Beams Pergolas",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 15,
        images: [
          '/images/hardwood/Cumaru/Cumaru 12x12 S4SE4E/Maximo Hardwood Cumaru 12x12 S4SE4E -1.jpg',
          '/images/hardwood/Cumaru/Cumaru 12x12 S4SE4E/Maximo Hardwood Cumaru 12x12 S4SE4E -2.jpg',
          '/images/hardwood/Cumaru/Cumaru 12x12 S4SE4E/_DSC0237.jpg',
        ]
    },
    {
        group: "Cumaru Deck tiles",
        name: "Maximo Hardwood Cumaru Deck Tiles",
        dimensions: "12x12 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Deck Tiles"],
            collection: "",
        },
        description: "Maximo Cumaru 12x12 deck tiles provide a simple, beautiful way to enhance outdoor areas. With a practical interlocking system, these tiles easily snap together, making assembly a breeze. Perfect for rooftops, concrete, or level surfaces, they bring Cumaru's warmth and durability to any outdoor space effortlessly.",
        features: [
            "Certified sustainable",
            "Easy installation",
            "Interlocking system for quick installation",
            "100% kiln-dried",
            "Suitable for all climates",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Deck Tiles",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 16,
        images: [
          '/images/hardwood/Garapa/Garapa 12x12 Deck Tiles S4SE4E/Maximo Hardwood GARAPA 12X12-1.jpg',
          '/images/hardwood/Garapa/Garapa 12x12 Deck Tiles S4SE4E/Maximo Hardwood GARAPA 12X12-2.jpg',
        ]
    },
    {
        group: "Cumaru Deck tiles",
        name: "Maximo Hardwood Cumaru Deck Tiles",
        dimensions: "24x24 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Deck Tiles"],
            collection: "",
        },
        description: "Maximo Cumaru 24x24 deck tiles offer a generous size and robust look, perfect for expansive outdoor designs. Equipped with quick connectors, they ensure easy and secure installation. Ideal for use on rooftops, concrete, and other level areas, they can also be elevated with pedestal systems to create a refined, above-ground aesthetic that showcases Cumaru's rich tones.",
        features: [
            "Certified sustainable",
            "Easy installation",
            "Quick connectors available",
            "100% Kiln Dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Deck Tiles",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 17,
        images: [
          '/images/hardwood/Garapa/Garapa 24x24 Deck Tiles S4SE4E/Maximo Hardwood GARAPA 24X24-1.jpg',
          '/images/hardwood/Garapa/Garapa 24x24 Deck Tiles S4SE4E/Maximo Hardwood GARAPA 24X24-2.jpg',
        ]
    },
    {
        group: "Garapa",
        name: "Maximo Hardwood Garapa",
        dimensions: "1x6 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking", "Fencing"],
            collection: "Standard",
        },
        description: "Maximo Hardwood Garapa 1x6 boards bring a natural golden tone that’s admired in outdoor spaces. While Garapa offers beautiful aesthetics, it doesn’t carry the same density as other hardwoods, making it a lighter option for decking and fencing projects. Its charm lies in its warmth and inviting look, perfect for those who want an elegant yet relaxed outdoor environment.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking Fencing",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 18,
        images: [
          '/images/hardwood/Garapa/1x6 S4SE4E/Maximo Hardwood Garapa 1x6 S4SE4E - 1.png',
          '/images/hardwood/Garapa/1x6 S4SE4E/Maximo Hardwood Garapa 1x6 S4SE4E -2.jpg',
          '/images/hardwood/Garapa/1x6 S4SE4E/garapa 1x6.webp',
        ]
    },
    {
        group: "Garapa",
        name: "Maximo Hardwood Garapa",
        dimensions: "5/4x6 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Decking"],
            collection: "Standard",
        },
        description: "Maximo Hardwood Garapa 5/4x6 boards provide the same warm golden tone with an added thickness for a more stable feel. Though Garapa isn’t as dense as other hardwood options, it remains a popular choice for decking due to its distinctive look and natural appeal. Perfect for creating inviting, sunlit spaces that stand out.",
        features: [
            "Certified sustainable",
            "100% kiln-dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Ipe",
            application: "Decking",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 19,
        images: [
          '/images/hardwood/Garapa/Garapa 5-4x6 S4SE4E/Maximo Hardwood Garapa 5-4x6 S4SE4E -1.jpg',
          '/images/hardwood/Garapa/Garapa 5-4x6 S4SE4E/Maximo Hardwood Garapa 5-4x6 S4SE4E -2.jpg',
          '/images/hardwood/Garapa/Garapa 5-4x6 S4SE4E/5.4x6 garapa.webp',
        ]
    },
    {
        group: "Cumaru Deck tiles",
        name: "Maximo Hardwood Cumaru Deck Tiles",
        dimensions: "12x12 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Deck Tiles"],
            collection: "",
        },
        description: "Maximo Garapa 12x12 deck tiles provide a simple, beautiful way to enhance outdoor areas. With a practical interlocking system, these tiles easily snap together, making assembly a breeze. Perfect for rooftops, concrete, or level surfaces, they bring Garapa's warmth and durability to any outdoor space effortlessly.",
        features: [
            "Certified sustainable",
            "Easy installation",
            "Interlocking system for quick installation",
            "100% kiln-dried",
            "Suitable for all climates",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Garapa",
            application: "Deck Tiles",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 20,
        images: [
          '/images/hardwood/Cumaru/Cumaru Deck Tiles 12x12 S4SE4E/Maximo Hardwood Cumaru 12X12-1.jpg',
          '/images/hardwood/Cumaru/Cumaru Deck Tiles 12x12 S4SE4E/Maximo Hardwood Cumaru 12X12-2.jpg',
        ]
    },
    {
        group: "Garapa Deck tiles",
        name: "Maximo Hardwood Garapa Deck Tiles",
        dimensions: "24x24 - S4SE4E",
        tag: {
            material: "Hardwood",
            application: ["Deck Tiles"],
            collection: "",
        },
        description: "Maximo Garapa 24x24 deck tiles offer a generous size and robust look, perfect for expansive outdoor designs. Equipped with quick connectors, they ensure easy and secure installation. Ideal for use on rooftops, concrete, and other level areas, they can also be elevated with pedestal systems to create a refined, above-ground aesthetic that showcases Garapa's rich tones.",
        features: [
            "Certified sustainable",
            "Easy installation",
            "Quick connectors available",
            "100% Kiln Dried",
            "Suitable for all climates",
            "Dimensionally stable",
            "Low maintenance",
            "Will weather into a beautiful silver color if left untreated",
            "From sustainably managed forests in South America",
        ],
        details: {
            species: "Garapa",
            application: "Deck Tiles",
            use: "Exterior, interior",
            finish: "Unoiled",
            durabilityClass: 1,
            warranty: "50 years",
            availableIn: "Random Lengths",
            boardLengths: "3-22ft",
        },
        id: 21,
        images: [
          '/images/hardwood/Cumaru/Cumaru Deck Tiles 24x24 S4SE4E/deck tile cumaru 1.webp',
          '/images/hardwood/Cumaru/Cumaru Deck Tiles 24x24 S4SE4E/deck tile cumaru 2.webp',
        ]
    },
];